// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"
)

type Message struct {
	ID        string
	UserID    string
	Message   string
	CreatedAt time.Time
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
}

type User struct {
	ID      string
	Account string
}
