// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import ()

type Session struct {
	ID     string
	UserID string
}

type User struct {
	ID           string
	AccountName  string
	PasswordHash string
}
