CREATE TABLE users (
	id TEXT PRIMARY KEY,
	account TEXT NOT NULL UNIQUE
);

CREATE TABLE sessions (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	expires_at DATETIME NOT NULL
);

CREATE TABLE messages (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	message TEXT NOT NULL,
	created_at DATETIME NOT NULL
);
