name: testing
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - run: |
          go get .
      - run: |
          make build
      - run: |
          go test -v ./...
